- id: '1587243611320'
  alias: Set default theme at startup
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: ios-dark-mode
    service: frontend.set_theme
- id: '1590194805152'
  alias: New Automation
  description: ''
  trigger:
  - at: 05:00:00
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: fan.sam_fan
    service: fan.turn_off
- id: '1592239027487'
  alias: Front Door Motion
  description: ''
  trigger:
  - platform: webhook
    webhook_id: Front_Door_Motion
  condition: []
  action:
  - data:
      message: Motion Detected
    service: notify.mobile_app_sams_iphone
