- id: '1587243611320'
  alias: Set default theme at startup
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: ios-dark-mode
    service: frontend.set_theme
- id: '1598730476786'
  alias: Match S Bedroom aux lights to main light
  description: ''
  trigger:
  - payload: HOLD
    platform: mqtt
    topic: cmnd/AllBedroomLights/POWER
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.sam_bedroom_light
        state: 'off'
      sequence:
      - data: {}
        entity_id: light.uni_tv_wled
        service: light.turn_off
    - conditions:
      - condition: state
        entity_id: light.sam_bedroom_light
        state: 'on'
      sequence:
      - data: {}
        entity_id: light.uni_tv_wled
        service: light.turn_on
    default: []
  mode: single
- id: '1598731005399'
  alias: Toggle S Bedroom aux and main lights
  description: ''
  trigger:
  - payload: TOGGLE
    platform: mqtt
    topic: cmnd/AllBedroomLights/POWER
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.sam_bedroom_light
        state: 'on'
      sequence:
      - data:
          entity_id:
          - light.sam_bedroom_light
          - light.uni_tv_wled
        service: light.turn_off
    - conditions:
      - condition: state
        entity_id: light.sam_bedroom_light
        state: 'off'
      sequence:
      - data:
          entity_id:
          - light.sam_bedroom_light
          - light.uni_tv_wled
        service: light.turn_on
    default: []
  mode: single
