esphome:
  name: serversensor
  platform: ESP8266
  board: nodemcuv2

# Enable Home Assistant API
api:
  password: !secret esp_home_api_ota

ota:
  password: !secret esp_home_api_ota

captive_portal:

# Enable logging
logger:

wifi:
  ssid: !secret WifiSSID
  password: !secret WifiPass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Serversensor Fallback Hotspot"
    password: "ho99Wvi0YyYZ"



sensor:
  - platform: homeassistant
    name: "Upstairs Temp from Home Assistant"
    entity_id: sensor.upstairs_temperature
    id: upstairstemp
  
  - platform: dht
    pin: D1
    id: tempSensor
    temperature: 
      name: Server Cupboard Temperature
      on_value_range:
        - above: 35.6
          then:
            - if:
                condition:
                  sensor.in_range:
                    id: upstairstemp
                    below: 26.5
                then:
                   - switch.turn_off: fans
                else:
                - homeassistant.service:
                    service: notify.mobile_app_sams_iphone
                    data: 
                      message: It works
        - below: 30.0
          then:
            - switch.turn_off: fans
    humidity:
      name: Server Cupboard Humidity
    update_interval: 10s
    model: DHT22

    
binary_sensor:
  - platform: gpio
    pin: 
      number: D5
      mode: INPUT_PULLUP
    name: "Server Cuboard Door"
    device_class: door
    on_press:
    - homeassistant.service:
        service: light.turn_on
        data: 
          entity_id: light.bridge
    on_release:
    - homeassistant.service:
        service: light.turn_off
        data: 
          entity_id: light.bridge
    
switch:
  - platform: gpio
    id: fans
    name: "Fans"
    pin: 
      number: D2
      inverted: yes
    

 
