esphome:
  name: window_sensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret WifiSSID
  password: !secret WifiPass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Window Sensor Fallback Hotspot"
    password: "F3yqguST7o4m"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_home_api_ota

ota:
  password: !secret esp_home_api_ota

binary_sensor:
  - platform: gpio
    pin: 
      number: D5
      mode: INPUT_PULLUP
    name: "Sam Bedroom Window"
    device_class: window
  - platform: gpio
    pin: 
      number: D6
      mode: INPUT_PULLUP
    name: "Lisa Bedroom Window"
    device_class: window
  - platform: gpio
    pin: 
      number: D7
      mode: INPUT_PULLUP
    name: "Office Window"
    device_class: window
    
    
    
sensor:
  - platform: dht
    pin: D1
    model: DHT22
    temperature:
      name: "Office Temperature"
    humidity:
      name: "Office Humidity"
    update_interval: 20s